name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pillow=10.3.0
  - pyqt=5.15.10
  - pytest=6.2.5
  - pytest-qt=3.3.0
  - libxkbcommon
  - libxcb
  - xorg-libx11
  - pip
